# Generated by Django 4.0.7 on 2022-10-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('travel_dist', models.FloatField()),
                ('SSID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_location', to='events.statesuburbs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('CI', 'Remember to fill in your wellness check'), ('FC', " hasn't checked in recently. Send a message?"), ('FA', 'Friend request accepted'), ('FQ', 'You have a friend request from '), ('FR', 'Friend request rejected'), ('RE', 'You may be interested in this event: '), ('UE', 'An event you are interested in is upcoming: ')], max_length=2)),
                ('content', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('link_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_event', to='events.events')),
                ('link_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_user', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LastCheckins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_interest', to='events.interests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='PendingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1_conf', models.BooleanField()),
                ('user_2_conf', models.BooleanField()),
                ('pending_user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_user_1', to=settings.AUTH_USER_MODEL)),
                ('pending_user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_user_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pending_user_1', 'pending_user_2')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'recipient', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user_1', to=settings.AUTH_USER_MODEL)),
                ('contact_user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contact_user_1', 'contact_user_2')},
            },
        ),
    ]
