# Generated by Django 4.0.7 on 2022-10-18 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user_1', to=settings.AUTH_USER_MODEL)),
                ('contact_user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contact_user_1', 'contact_user_2')},
            },
        ),
    ]
