# Generated by Django 4.0.7 on 2022-10-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attending',
            unique_together=set(),
        ),
    ]
