# Generated by Django 4.0.7 on 2022-10-19 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_attending_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='att_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attending',
            unique_together={('attending_user', 'attending_event')},
        ),
        migrations.RemoveField(
            model_name='attending',
            name='id',
        ),
    ]
