# Generated by Django 4.0.7 on 2022-10-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_attending_att_id_attending_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attending',
        ),
    ]
