# Generated by Django 4.0.7 on 2022-10-19 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_delete_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_event', to='events.events')),
                ('attending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('attending_user', 'attending_event')},
            },
        ),
    ]
