# Generated by Django 4.0.7 on 2022-10-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoopScoreState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('JBT', 'Jervis Bay Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], max_length=3)),
                ('score', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WoopScoreSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.statesuburbs')),
            ],
        ),
        migrations.CreateModel(
            name='WoopScoreIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(auto_now_add=True)),
                ('rsp', models.PositiveSmallIntegerField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_woop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmoteScoreSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.statesuburbs')),
            ],
        ),
        migrations.CreateModel(
            name='EmoteScoreIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(auto_now_add=True)),
                ('rsp', models.PositiveSmallIntegerField(choices=[(1, 'HAPPY'), (2, 'SATISFIED'), (3, 'NEUTRAL'), (4, 'SAD'), (5, 'DISTRESSED')])),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_emotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UID', 'dat')},
            },
        ),
    ]
