# Generated by Django 4.0.7 on 2022-10-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotescoreindividual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='emotescoress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='woopscoreindividual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='woopscoress',
            name='id',
        ),
        migrations.AddField(
            model_name='emotescoreindividual',
            name='key',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotescoress',
            name='key',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='woopscoreindividual',
            name='key',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='woopscoress',
            name='key',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
