# Generated by Django 4.0.7 on 2022-10-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0002_remove_emotescoreindividual_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emotescoreindividual',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emotescoreindividual',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='emotescoress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='woopscoreindividual',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='woopscoress',
            name='area',
        ),
        migrations.DeleteModel(
            name='WoopScoreState',
        ),
        migrations.DeleteModel(
            name='EmoteScoreIndividual',
        ),
        migrations.DeleteModel(
            name='EmoteScoreSS',
        ),
        migrations.DeleteModel(
            name='WoopScoreIndividual',
        ),
        migrations.DeleteModel(
            name='WoopScoreSS',
        ),
    ]
