# Generated by Django 4.0.7 on 2022-10-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0004_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emotescoreindividual',
            unique_together=set(),
        ),
    ]
