// defining the locations of a bunch of pngs that are stored locally (rather than on the backend)

export default {
    0: require("./assets/0.png"),
    1: require("./assets/1.png"),
    2: require("./assets/2.png"),
    3: require("./assets/3.png"),
    4: require("./assets/4.png"),
    5: require("./assets/5.png"),
    6: require("./assets/6.png"),
    7: require("./assets/7.png"),
    8: require("./assets/8.png"),
    9: require("./assets/9.png"),
    10: require("./assets/10.png"),
    11: require("./assets/11.png"),
    12: require("./assets/12.png"),
    13: require("./assets/13.png"),
    14: require("./assets/14.png"),
    15: require("./assets/15.png"),
    16: require("./assets/16.png"),
    17: require("./assets/17.png"),
    18: require("./assets/18.png"),
    19: require("./assets/19.png"),
    20: require("./assets/20.png"),
    21: require("./assets/21.png"),
    22: require("./assets/22.png"),
    23: require("./assets/23.png"),
    24: require("./assets/24.png"),
    25: require("./assets/25.png"),
    26: require("./assets/26.png"),
    27: require("./assets/27.png"),
    28: require("./assets/28.png"),
    29: require("./assets/29.png"),
    30: require("./assets/30.png"),
    31: require("./assets/31.png"),
    32: require("./assets/32.png"),
    33: require("./assets/33.png"),
    34: require("./assets/34.png"),
    35: require("./assets/35.png"),
    36: require("./assets/36.png"),
    // 37: require("./assets/37.png"),
    38: require("./assets/38.png"),
    39: require("./assets/39.png"),
    40: require("./assets/40.png"),
    41: require("./assets/41.png"),
    42: require("./assets/42.png"),
    43: require("./assets/43.png"),
    44: require("./assets/44.png"),
    45: require("./assets/45.png"),
    46: require("./assets/46.png"),
    47: require("./assets/47.png"),
    48: require("./assets/48.png"),
    49: require("./assets/49.png"),
    50: require("./assets/50.png"),
    51: require("./assets/51.png"),
    52: require("./assets/52.png"),
    53: require("./assets/53.png"),
    // 54: require("./assets/54.png"),
    55: require("./assets/55.png"),
    56: require("./assets/56.png"),
    57: require("./assets/57.png"),
    58: require("./assets/58.png")
}